services:
  - type: web
    name: bank-ledger-system
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: REFRESH_TOKEN
        sync: false
